### ISSUE TITLE
Problems with exception handling screenshot

### ISSUE THREAD

**Issue by grawk** [paypal/nemo-screenshot#48]
If the "exception" event screenshot is enabled, mocha tests can hang. The thrown exception doesn't bubble up to the mocha handler. In that case the current test may not fail until a timeout.

I'm not entirely certain why, but if the handler is attached with `once` instead of `on`, the behavior is better. I.e. at least the exception bubbles up to mocha. This will fail the current test. The downside is that the uncaughtException handler won't respond to further uncaughtException events in the same webdriver session.

**Comment by nikulkarni** [comment]
I'm not able to reproduce this. I wrote a unit test under nemo-screenshot in which exception event is enabled. Unit test is something like this

``` javascript
  it('will use @exeption@ to take a screenshot', function (done) {
    nemo.driver.get('www.google.com');
    nemo.driver.findElement(nemo.wd.By.name('foo')); //this will trigger exception
  }); 
```

I correctly get output like below and test doesn't hang.

```
NoSuchElementError: {"errorMessage":"Unable to find element with name 'foo'","request":{"headers":{"Accept":"application/json; charset=utf-8","Connection":"close","Content-Length":"30","Content-Type":"application/json;charset=UTF-8","Host":"192.168.1.108:65400"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"name\",\"value\":\"foo\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/7f12d680-4157-11e6-a681-2bed6f95bb6c/element"}}
    at new bot.Error (/Users/nikulkarni/Documents/workspace/nemo-screenshot/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
    at Object.bot.response.checkResponse (/Users/nikulkarni/Documents/workspace/nemo-screenshot/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)
    at /Users/nikulkarni/Documents/workspace/nemo-screenshot/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:379:20
    at promise.Promise.goog.defineClass.invokeCallback_ (/Users/nikulkarni/Documents/workspace/nemo-screenshot/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1337:14)
    at promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (/Users/nikulkarni/Documents/workspace/nemo-screenshot/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (/Users/nikulkarni/Documents/workspace/nemo-screenshot/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (/Users/nikulkarni/Documents/workspace/nemo-screenshot/node_modules/selenium-webdriver/lib/goog/async/run.js:124:15)
    at process._tickCallback (node.js:377:9)
nemo-screenshot::{"imageName":"/Users/nikulkarni/Documents/workspace/nemo-screenshot/test/report/ScreenShot_onException-26979-1467575473789.png","imagePath":"/Users/nikulkarni/Documents/workspace/nemo-screenshot/test/report/Users/nikulkarni/Documents/workspace/nemo-screenshot/test/report/ScreenShot_onException-26979-1467575473789.png"}::nemo-screenshot
```

**Comment by grawk** [comment]
I'm also no longer able to reproduce..
