### ISSUE TITLE
Nemo-screenshot v3 has this TypeError when use with "click"

### ISSUE THREAD

**Issue by mengchen2** [paypal/nemo-screenshot#61]
TypeError: nemo.screenshot.snap(...).then is not a function
      at WebElementPromise.nemo.wd.WebElement.click (node_modules/nemo-screenshot/index.js:201:22)
      at Context.<anonymous> (test/functional/spec/flow/bizwalletnodeweb/amount.js:26:52)

**Comment by grawk** [comment]
need to modify the returned promise from snap to check for native promises. also for webdriver promise, check new syntax

**Comment by grawk** [comment]
@mengchen2 PR #64 should resolve this when published

**Comment by grawk** [comment]
should be fixed with v3.0.1
