### ISSUE TITLE
ManagedPromiseError: Creating a new managed Promise. 

### ISSUE THREAD

**Issue by emailtomit** [paypal/nemo-screenshot#69]
2018-01-26T22:18:17Z] [WARNING] [promise.ControlFlow] ManagedPromiseError: Creating a new managed Promise. This call will fail when the promise manager is disabled
    at new Deferred (/Users/node_modules/selenium-webdriver/lib/promise.js:1454:20)
    at Object.defer (/Users/node_modules/selenium-webdriver/lib/promise.js:1555:12)
    at p (/Users/node_modules/nemo-screenshot/index.js:23:31)
    at Object.snap (/Users/node_modules/nemo-screenshot/index.js:146:32)
    at /Users/test/functional/spec/test111.js:73:33
    at ManagedPromise.invokeCallback_ (/Users/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/Users/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Users/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/Users/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /Users/node_modules/selenium-webdriver/lib/promise.js:668:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by grawk** [comment]
Thanks @emailtomit. Should be able to get to this in the next few days.
